version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=foo
      - MONGODB_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=google-docs-clone
    ports:
      - 27017:27017
    user: 1000:1000
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
